# Generated by Django 3.2.9 on 2021-12-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='氏名')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='年齢')),
            ],
        ),
    ]
